# Generated by Django 5.2.7 on 2025-10-27 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('organization', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('requirements', models.TextField()),
                ('amount', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('education_level', models.CharField(choices=[('UNDERGRADUATE', 'Undergraduate'), ('MASTERS', 'Masters'), ('PHD', 'PhD'), ('POSTDOC', 'Post-Doctoral'), ('ALL', 'All Levels')], max_length=20)),
                ('deadline', models.DateField()),
                ('website_url', models.URLField()),
                ('source_website', models.CharField(max_length=100)),
                ('field_of_study', models.CharField(max_length=200)),
                ('is_fully_funded', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['title', 'organization'], name='scholarship_title_6465be_idx'), models.Index(fields=['country'], name='scholarship_country_607050_idx'), models.Index(fields=['education_level'], name='scholarship_educati_7cd675_idx'), models.Index(fields=['deadline'], name='scholarship_deadlin_f24616_idx')],
            },
        ),
        migrations.CreateModel(
            name='ScholarshipApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('SAVED', 'Saved'), ('APPLIED', 'Applied'), ('IN_PROGRESS', 'In Progress'), ('REJECTED', 'Rejected'), ('ACCEPTED', 'Accepted')], default='SAVED', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('applied_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scholarship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scholarships.scholarship')),
            ],
        ),
    ]
